"""
abt/math/definitions.py
=======================
Executable encodings of every formal definition in the paper.

Definitions:
  Definition 1 – Rooted Binary Tree
  Definition 2 – Depth and Height
  Definition 3 – Perfect Binary Tree
  Definition 4 – Value Assignment
  Definition 5 – Sibling Pair
  Definition 6 – Average Binary Tree (ABT operator)
  Definition 7 – WABT
  Definition 8 – MBT
  Definition 9 – PBT

Reference: Paper Section III.
"""

from __future__ import annotations

import math
import statistics
from typing import Optional, Tuple

from abt.core import Node, validate_perfect, height as tree_height


# ---------------------------------------------------------------------------
# Definition 1 – Rooted Binary Tree  (structural check)
# ---------------------------------------------------------------------------

def is_rooted_binary_tree(root: Optional[Node]) -> bool:
    """Return True iff the tree rooted at *root* is a valid rooted binary tree.

    Each node has at most two ordered successors (left, right).
    Definition 1: T = (V, E, r).
    """
    if root is None:
        return True  # empty tree is trivially valid
    stack = [root]
    visited = set()
    while stack:
        n = stack.pop()
        if id(n) in visited:
            return False  # cycle detected
        visited.add(id(n))
        if n.left:
            stack.append(n.left)
        if n.right:
            stack.append(n.right)
    return True


# ---------------------------------------------------------------------------
# Definition 2 – Depth and Height
# ---------------------------------------------------------------------------

def depth(root: Optional[Node], target: Node) -> int:
    """Return the depth of *target* in the tree rooted at *root*.

    d_T(v) = number of edges from root to v.
    Returns -1 if target is not found.

    Definition 2: d_T(v), h(T) = max_{v in V} d_T(v).
    """
    if root is None:
        return -1
    if root is target:
        return 0
    stack = [(root, 0)]
    while stack:
        node, d = stack.pop()
        if node is target:
            return d
        if node.left:
            stack.append((node.left, d + 1))
        if node.right:
            stack.append((node.right, d + 1))
    return -1


# ---------------------------------------------------------------------------
# Definition 3 – Perfect Binary Tree
# ---------------------------------------------------------------------------

def is_perfect_binary_tree(root: Optional[Node]) -> bool:
    """Return True iff *root* is a perfect binary tree.

    Perfect: every internal node has exactly two children and every
    leaf is at depth h(T).

    A perfect binary tree of height h has |V| = 2^(h+1) - 1 nodes.

    Definition 3.
    """
    try:
        validate_perfect(root)
        return True
    except ValueError:
        return False


def expected_node_count(h: int) -> int:
    """Return 2^(h+1) - 1, the node count of a perfect binary tree of height h."""
    return (1 << (h + 1)) - 1


# ---------------------------------------------------------------------------
# Definition 4 – Value Assignment
# ---------------------------------------------------------------------------

def value_at(node: Node) -> float:
    """Return w(v), the real-valued payload of *node*.

    Definition 4: w : V -> R.
    """
    return node.val


# ---------------------------------------------------------------------------
# Definition 5 – Sibling Pair
# ---------------------------------------------------------------------------

def sibling_pair(p: Node) -> Tuple[float, float]:
    """Return the sibling pair (w(L(p)), w(R(p))) generated by internal node p.

    Definition 5: (L(p), R(p)) is the sibling pair of p.

    Raises
    ------
    ValueError
        If p is a leaf (no children).
    """
    if p.left is None or p.right is None:
        raise ValueError(f"Node({p.val}) is a leaf — no sibling pair.")
    return (p.left.val, p.right.val)


# ---------------------------------------------------------------------------
# Definition 6 – ABT operator   (core formula only; full impl in core.py)
# ---------------------------------------------------------------------------

def abt_node_value(v1: float, v2: float) -> float:
    """Compute w'(f(p)) = (v1 + v2) / 2.

    This is Equation (1) from the paper.

    Definition 6(D2).
    """
    return (v1 + v2) / 2.0


# ---------------------------------------------------------------------------
# Definition 7 – WABT
# ---------------------------------------------------------------------------

def wabt_node_value(v1: float, v2: float, w1: float, w2: float) -> float:
    """Compute the WABT node value.

    Equation (2): w'(u) = (omega1 * v1 + omega2 * v2) / (omega1 + omega2).

    Reduces to the ABT mean when w1 == w2.

    Definition 7.

    Raises
    ------
    ValueError
        If w1 or w2 are not positive.
    """
    if w1 <= 0 or w2 <= 0:
        raise ValueError(f"WABT weights must be positive, got w1={w1}, w2={w2}.")
    return (w1 * v1 + w2 * v2) / (w1 + w2)


# ---------------------------------------------------------------------------
# Definition 8 – MBT
# ---------------------------------------------------------------------------

def mbt_node_value(v1: float, v2: float) -> float:
    """Compute the MBT node value.

    Equation (3): w'(u) = median(v1, v2) = (v1 + v2) / 2 for two elements.

    For two values the sample median equals the mean.
    The MBT becomes structurally distinct for k-ary trees (k >= 3).

    Definition 8.
    """
    return statistics.median([v1, v2])


# ---------------------------------------------------------------------------
# Definition 9 – PBT
# ---------------------------------------------------------------------------

def pbt_node_value(v1: float, p1: float, v2: float, p2: float) -> float:
    """Compute the PBT node value.

    Equation (4): w'(u) = E[X] = p(v1)*v1 + p(v2)*v2,
    where p(v1) + p(v2) = 1.

    Definition 9.

    Raises
    ------
    ValueError
        If probabilities are negative or don't sum to 1.
    """
    if p1 < 0 or p2 < 0:
        raise ValueError(f"PBT probabilities must be non-negative, got {p1}, {p2}.")
    if not math.isclose(p1 + p2, 1.0, abs_tol=1e-9):
        raise ValueError(f"PBT probabilities must sum to 1, got {p1 + p2}.")
    return p1 * v1 + p2 * v2
